// output/vue/vue3/src/components/MyComponent.vue
<template>
  <div>
    {{ message || "Hello" }} {{ name }}! I can run in React, Vue, Solid or
    Svelte!
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "my-basic-component",

  props: ["message"],

  data() {
    return { name: "Foo" };
  },
});
</script>

// output/react/src/components/MyComponent.jsx
"use client";
import * as React from "react";
import { useState } from "react";

function MyBasicComponent(props) {
  const [name, setName] = useState(() => "Foo");

  return (
    <div>
      {props.message || "Hello"}
      {name}! I can run in React, Vue, Solid or Svelte!
    </div>
  );
}

export default MyBasicComponent;
